[project]
name = "thorlabs-apt"
version = "0.0.1"
description = "Python implementation of the Thorlabs APT communication protocol."
authors = [
    { name = "David Bakker", email = "david.bakker@tno.nl" },
]
readme = "README.md"
requires-python = ">=3.12"
keywords = ["device", "control"]
dependencies = [
    "pyserial>=3.5",    
]
classifiers = [
    "Programming Language :: Python :: 3",
]

[dependency-groups]
dev = [
    "coverage>=7.6.0",
    "ty>=0.0.69",
    "tox>=4.52.0",
    "pytest>=8.2.2",
    "ruff>=0.5,<0.13"
]

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = ["apps"]

[tool.ruff.lint]
preview = true
select = [
    "A", # flake8-builtins
    "ANN", # flake8-annotations
    "ASYNC", # flake8-async
    "B", # flake8-bugbear
    "BLE", # flake8-blind-except
    "COM", #flake8-commas
    "C4", #flake8-comprehensions
    "C90", # mccabe
    #"D", # pydocstyle
    "DTZ", # flake8-datetimez
    "E", # pycodestyle (error)
    "ERA", # eradicate
    "EM", # flake8-errmsg
    "EXE", # flake8-executable
    "F", # Pyflakes
    "FA", # flake8-future-annotations
    "FBT", # flake8-boolean-trap
    "FIX", # flake8-fixme
    "FLY", # flynt
    "G", # flake8-logging-format
    "I", # isort
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "LOG", # flake8-logging
    "N", # pep8-naming
    "NPY", # NumPy-specific rules
    "PD", # pandas-vet
    "PERF", # Perflint
    "PIE", # flake8-pie
    "PT", # flake8-pytest-style
    "PTH", # flake8-use-pathlib
    "FURB", # refurb
    "RET", # flake8-return
    "RUF", # Ruff-specific rules
    "RUF022",
    "S", # flake8-bandit
    "SIM", # flake8-simplify
    "SLF", # flake8-self
    "SLOT", # flake8-slots
    "TCH", # flake8-type-checking
    "TRY", # tryceratops
    "T20", # flake8-print
    "T100", # flake8-debugger
    "UP", # pyupgrade
    "W", # pycodestyle (warning)
    "Q", # flake8-quotes
    "YTT", # flake8-2020
]
ignore = [
    "A005", # module shadowing a Python builtin module
    "ANN401", # typing.Any can be useful (for example in __eq__)
    "B027", # Ignore the rule for empty methods in abstract base classes
    "COM812", # Conflicts with ruff format
    "ISC001", # Possible conflicts with ruff format
    "W605", # deprecated in Python 3.6
    "A001", 
    "A002",
    "N801",
    "FBT001",
]
isort.combine-as-imports = true
pydocstyle.convention = "google"

[tool.ruff.lint.extend-per-file-ignores]
"*.py" = [
    "S101", # asserts allowed everywhere
]
"test/**/*.py" = [
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    "D", # No doc requirements in tests
    "SLF001", # Testing private functions is OK
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["thorlabs_apt"]

